/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BabyBanner: typeof import('./src/components/home/BabyBanner.vue')['default']
    BottleMilkForm: typeof import('./src/components/feeding/forms/BottleMilkForm.vue')['default']
    BottomTabBar: typeof import('./src/components/BottomTabBar.vue')['default']
    BreastMilkForm: typeof import('./src/components/feeding/forms/BreastMilkForm.vue')['default']
    DaySummaryCard: typeof import('./src/components/feeding/DaySummaryCard.vue')['default']
    DiaperForm: typeof import('./src/components/feeding/forms/DiaperForm.vue')['default']
    FeatureGrid: typeof import('./src/components/home/FeatureGrid.vue')['default']
    FeedingFormPopup: typeof import('./src/components/feeding/FeedingFormPopup.vue')['default']
    FeedingNavBar: typeof import('./src/components/feeding/FeedingNavBar.vue')['default']
    FeedingQuickBar: typeof import('./src/components/feeding/FeedingQuickBar.vue')['default']
    FeedingTimeline: typeof import('./src/components/feeding/FeedingTimeline.vue')['default']
    FilterPopup: typeof import('./src/components/feeding/FilterPopup.vue')['default']
    FormulaForm: typeof import('./src/components/feeding/forms/FormulaForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SleepForm: typeof import('./src/components/feeding/forms/SleepForm.vue')['default']
    SolidFoodForm: typeof import('./src/components/feeding/forms/SolidFoodForm.vue')['default']
    Timeline: typeof import('./src/components/home/Timeline.vue')['default']
    TodayChanges: typeof import('./src/components/home/TodayChanges.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSlider: typeof import('vant/es')['Slider']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    WaterForm: typeof import('./src/components/feeding/forms/WaterForm.vue')['default']
  }
}
